export const Icons = {
  arrow_left: require('./arrow-wide-left-bold.png'),
  save: require('./save-basic-bold.png'),
  settings: require('./settings.png'),
  arrow_right: require('./arrow-right.png'),
  arrow_down: require('./arrow-down.png'),
  arrow_small: require('./arrow-small.png'),
  arrow_up: require('./arrow-up.png'),
  level_basic: require('./basic.png'),
  sustainability: require('./sustainability.png'),
  health: require('./health.png'),
  reviews: require('./reviews.png'),
  recycling: require('./recycling.png'),
  info: require('./info.png'),
  info_bold: require('./info-bold.png'),
  energy: require('./energy.png'),
  water: require('./water.png'),
  nature: require('./nature.png'),
  emission: require('./emission.png'),
  ghg: require('./ghg.png'),
  encroachment: require('./encroachment.png'),
  close: require('./close.png'),
  
};